### ISSUE TITLE
install layouts

### ISSUE THREAD

**Issue by brianteeman** [coolcat-creations/plg_fields_travel#4]
https://github.com/coolcat-creations/plg_fields_travel/blob/bfb2bb87b12035cdf9d148637bc8ae160cbd51c7/travel/travel.xml#L21

is this the bit you said doesnt work?

if so should it not be done the same as when you add files to media?

**Comment by coolcat-creations** [comment]
Not possible in joomla now, i´d need an own file extension - will do that later. For now we have to move it manually. 
Note: that it´s just needed for usage within the editor {field id, weather} and when automatic display is off.
